interface SafetyCheckListModel{
    id: Number,
    patId: Number,
    visitId: Number,
    ipId: Number,
    airway:Number,
    allergy:Number,
    anticipatedBlood:Number,
    bloodloss:Number,
    confermation:Number,
    critical:Number,
    equipmentIssues:Number,
    equipmentProblems:Number,
    imaging:Number,
    incision:Number,
    marked:Number,
    medication:Number,
    oximeter:Number,
    patientSpecific:Number,
    procedures:Number,
    prophylaxis:Number,
    recovery:Number,
    specimen:Number,
    sponge:Number,
    sterility:Number,
    teamMembers:Number,
    timeTaken:Number,
    dtm:String,
    surgName:String,
    docId:Number
}

const SafetyCheckListSaveFormat = {
    id: 0,
    patId: 0,
    visitId: 0,
    ipId: 0,
    airway:0,
    allergy:0,
    anticipatedBlood:0,
    bloodloss:0,
    confermation:0,
    critical:0,
    equipmentIssues:0,
    equipmentProblems:0,
    imaging:0,
    incision:0,
    marked:0,
    medication:0,
    oximeter:0,
    patientSpecific:0,
    procedures:0,
    prophylaxis:0,
    recovery:0,
    specimen:0,
    sponge:0,
    sterility:0,
    teamMembers:0,
    timeTaken:0,
    dtm:'0000-00-00 00:00:00',
    surgName:'',
    docId:0
}
export { type SafetyCheckListModel,SafetyCheckListSaveFormat }